version: "3.8"

networks:
  monitoring:      # A dedicated network for Prometheus & Node Exporter
  app:             # Network for frontend & backend

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    restart: unless-stopped
    networks:
      - app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - backend-data:/app/data
    environment:
      - ENV=production
    restart: unless-stopped
    networks:
      - app
      - monitoring  # so Prometheus can scrape metrics

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
      - node-exporter
    restart: unless-stopped
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - monitoring

volumes:
  backend-data:
    name: fusionpact_backend_data
